import "./globals.css";
import { KoHo } from "next/font/google";

const koho = KoHo({
  weight: ["200", "400"],
  subsets: ["latin"],
  preload: true,
  fallback: "Inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navStyle = {
  navBackground: {
    backgroundColor: "#D9D9D9",
    display: "flex",
    flexDirection: "row",
    width: "30vw",
    padding: "1vw",
    margin: "1vw",
    position: "fixed",
    right: "0",
    borderRadius: "40px",
    zIndex: "10",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={koho.className}>
        <div style={navStyle.navBackground}>hiii</div>
        {children}
      </body>
    </html>
  );
}
